### ISSUE TITLE
Missing protocol63454

### ISSUE THREAD

**Issue by scseb** [Blizzard/s2protocol#72]
Hi. A replay from today asks for protocol63454. Will this protocol be uploaded soon?
I see it has been a recent problem with delayed protocols. Is there a way to get your hands
on the newest protocol other than this site?

**Comment by amartin916** [comment]
I have been using protocol 62848 as a replacement for 63454 for the last few weeks on sc2replaystats and it seems to be working as you would expect. 

Not a great solution as it does not work with every release but I don't believe anything changed between 62848 -> 63454

**Comment by scseb** [comment]
How do you use an old protocol as a replacement. Make a copy of the protocol62848.py file and rename it protocol63454.py ?

**Comment by amartin916** [comment]
Yep copy and paste and rename the file 😀

**Comment by scseb** [comment]
thx. I will try that!

**Comment by Cinetik** [comment]
fixed with latests commit

**Comment by scseb** [comment]
Thx. It now works with replays from today. The protocol63454.py is still missing though, but guess I can manage with amartin916's advice.

**Comment by jashunk** [comment]
I submitted a pull request for protocol63454.py.

**Comment by scseb** [comment]
Thx. It works now.
